### ISSUE TITLE
Android foreground notification is not cleared after position Stream is cancelled

### ISSUE THREAD

**Issue by ValentinTaleb** [Baseflow/flutter-geolocator#1142]
## 🐛 Bug Report

On Android, it's possible display a foreground notification in order to keep recording location updates even after the user has moved the app in the background.

This notification does not disappear after the position stream as been cancelled.

### Expected behavior

The Android foreground notification should disappear once the position stream has been cancelled.

### Reproduction steps

```
StreamSubscription<Position>? _positionStreamSubscription;

@override
void initState() {
  super.initState();

  if (Platform.isAndroid) {
    locationSettings = AndroidSettings(
      ...
      foregroundNotificationConfig: ForegroundNotificationConfig(
        notificationTitle: 'Notification title',
        notificationText: 'Notification text',
        notificationIcon: const AndroidResource(name: 'ic_notification', defType: 'drawable'),
      ));
  }

  _positionStreamSubscription = Geolocator.getPositionStream(locationSettings: locationSettings).listen(
    ...
  );
}

@override
void dispose() {
  _positionStreamSubscription.cancel();

  super.dispose();
}
```

### Configuration

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

Thank you very much in advance

**Comment by ValentinTaleb** [comment]
Am I the only one who experiences this issue?

**Comment by Juan-EZ** [comment]
I am experiencing the same issue. The notification persists even after I force close the app on Android

**Comment by fleoparra** [comment]
Same problem here. Notification continues after cancel the stream.

**Comment by MrCheese02** [comment]
I can confirm the same problem. After all subscriptions are cancelled I receive the following log messages:
```
E/FlutterGeolocator( 9409): Geolocator position updates stopped
E/FlutterGeolocator( 9409): There is still another flutter engine connected, not stopping location service
E/FlutterGeolocator( 9409): Geolocator position updates started
```
However, upon the app's and the Geolocator service's startup it only reports about one connection to the Flutter engine.
```
D/FlutterGeolocator(11402): Attaching Geolocator to activity
D/FlutterGeolocator(11402): Creating service.
D/FlutterGeolocator(11402): Binding to location service.
D/FlutterGeolocator(11402): Geolocator foreground service connected
D/FlutterGeolocator(11402): Initializing Geolocator services
D/FlutterGeolocator(11402): Flutter engine connected. Connected engine count 1
```

**Comment by habanoz** [comment]
> I can confirm the same problem. After all subscriptions are cancelled I receive the following log messages:
> 
> ```
> E/FlutterGeolocator( 9409): Geolocator position updates stopped
> E/FlutterGeolocator( 9409): There is still another flutter engine connected, not stopping location service
> E/FlutterGeolocator( 9409): Geolocator position updates started
> ```
> 
> However, upon the app's and the Geolocator service's startup it only reports about one connection to the Flutter engine.
> 
> ```
> D/FlutterGeolocator(11402): Attaching Geolocator to activity
> D/FlutterGeolocator(11402): Creating service.
> D/FlutterGeolocator(11402): Binding to location service.
> D/FlutterGeolocator(11402): Geolocator foreground service connected
> D/FlutterGeolocator(11402): Initializing Geolocator services
> D/FlutterGeolocator(11402): Flutter engine connected. Connected engine count 1
> ```

Same

**Comment by alkammar** [comment]
Same problem. It started to happen to me when I added a plugin that runs a service besides the service from the geolocator plugin. If a remove that plugin the location service is closed properly. Seems it does not check which type of service is running or mistakenly thinks the other plugin's service is also a location service.

**Comment by bazrafkan** [comment]
Same problem 
geolocator: ^9.0.2

**Comment by Wackymax** [comment]
I will have a look at this

**Comment by ValentinTaleb** [comment]
> I will have a look at this

Thank you very much @Wackymax

**Comment by mvanbeusekom** [comment]
Version 4.1.4 of the `geolocator_android` package was just released which if I understand correctly should resolve this issue. Would it be possible for someone to test this and let us know?

To get the latest version run `flutter pub upgrade` in your project.

**Comment by MrCheese02** [comment]
> Version 4.1.4 of the `geolocator_android` package was just released which if I understand correctly should resolve this issue. Would it be possible for someone to test this and let us know?
> 
> To get the latest version run `flutter pub upgrade` in your project.

For me the upgrade resolved the issue. Thank you for the fast response to it @Wackymax @mvanbeusekom !

**Comment by bazrafkan** [comment]
For me too after upgrade is working. Thanks @Wackymax @mvanbeusekom

**Comment by mvanbeusekom** [comment]
Thanks for the feedback and active responses to help debug this issue. I am going to close this issue. If any future problems occur please report it as a new issue.

**Comment by DucLQ92** [comment]
I am still experiences this issue.
flutter 2.10.5
geolocator: ^9.0.2
geolocator_android: ^4.1.7

**Comment by Stypox** [comment]
I looked through [the code](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator_android/android/src/main/java/com/baseflow/geolocator/StreamHandlerImpl.java#L153-L158) and apparently the message can still appear when the Android foreground notification is not used. In that case the message is misleading, since the foreground location service is not being used at all, so there is no need to stop it. The position updates are stopped correctly, though.
